language: csharp
mono: none
dotnet: 3.1
script:
- dotnet build
before_deploy: dotnet tool install -g Amazon.Lambda.Tools
deploy:
  provider: script
  script: ~/.dotnet/tools/dotnet-lambda deploy-serverless --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-key ${AWS_SECRET_ACCESS_KEY} -tp 'TelegramAPIToken=${TELEGRAM_API_TOKEN};KandilliPageUrl=${KANDILLI_PAGE_URL}'
  skip_cleanup: true
  on:
    branch: master