name: Deploy Lambda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup-dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: build
      run: dotnet build
    - name: install aws lambda tool
      if: ${{ github.ref == 'refs/heads/master' }}
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: deploy
      if: ${{ github.ref == 'refs/heads/master' }}
      run:  ~/.dotnet/tools/dotnet-lambda deploy-serverless --aws-access-key-id ${AWS_ACCESS_KEY_ID} --aws-secret-key ${AWS_SECRET_ACCESS_KEY} -tp 'TelegramAPIToken=${TELEGRAM_API_TOKEN};KandilliPageUrl=${KANDILLI_PAGE_URL}'